# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3eecca3a3564da5b8c702c81fe86345f5567645b95203fcf502b7ce89f7af8c3779f1bd84a3a8f0bed108731cb5d97c11e32e73fbf2a4606b9a905ac9598949

test:
  secret_key_base: 8415da2d978f51123996edbefe91e7a458fc8ce743d09e31bbff63e6b2493cfaac4edfac80cf7c07d3d51bb3c00ef50e3fe40083753aab587615d8c95bcbc635

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
