User.create!([
  {firstname: "jeffrey", lastname: "the frog", email: "test@example.com", language: nil, gender: nil, current_location: "jericho", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "ian", lastname: "humphrington", email: "test1@example.com", language: nil, gender: nil, current_location: "jericho", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "test", lastname: "test", email: "test2@example.com", language: nil, gender: nil, current_location: "bradford", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "tse", lastname: "tse", email: "test3@example.com", language: nil, gender: nil, current_location: "huntingdon", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "barry", lastname: "bother", email: "test4@example.com", language: nil, gender: nil, current_location: "shropshire", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "barry", lastname: "barry", email: "test5@example.com", language: nil, gender: nil, current_location: "bognor regis", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "barry", lastname: "varry", email: "test6@example.com", language: nil, gender: nil, current_location: "belize", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "lottie", lastname: "smith", email: "test66@example.com", language: nil, gender: nil, current_location: "grantham", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "quintus", lastname: "blb", email: "test666@example.com", language: nil, gender: nil, current_location: "bradford", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "jefrry", lastname: "blb", email: "test76@example.com", language: nil, gender: nil, current_location: "bradford", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "bdlndkjdkf", lastname: "kjdkf", email: "test88@example.com", language: nil, gender: nil, current_location: "jericho", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "this", lastname: "that ", email: "tesdjt@example.com", language: nil, gender: nil, current_location: "bradford", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "this", lastname: "that", email: "sadf@example.com", language: nil, gender: nil, current_location: "london", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil},
  {firstname: "Donald", lastname: "Wade", email: "tdddest@example.com", language: nil, gender: nil, current_location: "New Jersey", search_history: nil, date_of_birth: nil, education: nil, profession: nil, other_information: nil}
])
